#!/bin/bash

###########################################################
# Installer for edulutionUI
# V1.0
# by lukas.spitznagel@netzint.de
###########################################################

DIRECTORY="/srv/docker/edulution-ui/"

clear

cat <<EOF
           _       _       _   _             _   _ ___ 
   ___  __| |_   _| |_   _| |_(_) ___  _ __ | | | |_ _|
  / _ \/ _\` | | | | | | | | __| |/ _ \| '_ \| | | || | 
 |  __/ (_| | |_| | | |_| | |_| | (_) | | | | |_| || | 
  \___|\__,_|\__,_|_|\__,_|\__|_|\___/|_| |_|\___/|___|
                                                       
                edulutionUI - Installer

EOF

if [ "$EUID" -ne 0 ]; then
  echo "[!] Bitte führen Sie das Skript mit Root-Rechten aus."
  exit 1
fi

if [ -d "$DIRECTORY" ]; then
  echo "[!] Die edulutionUI scheint bereits installiert zu sein. Bitte prüfe das Verzeichnis '$DIRECTORY'!"
  exit 1
fi


if ! command -v docker &> /dev/null; then
    echo "[*] Docker ist nicht installiert. Installation wird gestartet..."

    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    else
        echo "[!] Betriebssystem konnte nicht ermittelt werden."
        exit 1
    fi

    if [ "$OS" == "ubuntu" ] && ([[ "$VERSION" == "22.04" ]] || [[ "$VERSION" == "24.04" ]]); then

        apt-get update

        apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
            gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

        apt-get update

        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        systemctl enable docker --now

        echo "[*] Docker wurde erfolgreich installiert."

    else
        echo "[!] Dieses Skript unterstützt nur Ubuntu 22.04 und 24.04."
        exit 1
    fi
else
    echo "[*] Docker ist bereits installiert."
fi

if ! command -v jq &> /dev/null; then
    echo "[*] JQ ist nicht installiert. Installation wird gestartet..."
    apt-get update
    apt-get install -y jq
fi

echo "[*] Erstelle Ordner für die edulutionUI installation..."
mkdir -p $DIRECTORY
cd $DIRECTORY

for file in docker-compose.yml realm-edulution.json traefik.yml edulution-default.yml; do

    echo "[*] Herunterladen der Datei $file..."
    curl -s -o ${DIRECTORY}${file} https://get.edulution.io/download/${file}.template

    if [ ! -f "${DIRECTORY}${file}" ]; then
        echo "[!] Datei '$file' konnte nicht heruntergeladen werden!"
        exit 1
    fi

done

echo "[*] Anpassung der Proxy-Konfiguration..."
mkdir -p ${DIRECTORY}data/traefik/config
mv ${DIRECTORY}edulution-default.yml ${DIRECTORY}data/traefik/config

echo "[*] Starte den edulutionUI Web-Installer..."

docker pull ghcr.io/edulution-io/edulution-installer:main 2>&1 > /dev/zero

cat <<EOF

########################################################

    edulutionUI Web-Installer
      
    Sie erreichen die Oberfläche wie folgt:
      
    https://$(hostname):443
    https://$(hostname -I | awk '{print $1}'):443

########################################################

EOF

docker run -it --name edulution-installer -p 443:8000 -v ${DIRECTORY}:/edulution-ui/ ghcr.io/edulution-io/edulution-installer:main 2>&1 > /dev/zero
docker rm edulution-installer 2>&1 > /dev/zero

echo "[*] Starte den Authentifizierungserver um die Einstellungen festzulegen..."

docker network create edulution-prepare 2>&1 > /dev/zero

docker run -d \
  --name edulution-keycloak-db \
  --restart always \
  --env-file ${DIRECTORY}edulution.env \
  -e POSTGRES_DB=keycloak \
  -v ${DIRECTORY}data/keycloak/db:/var/lib/postgresql/data \
  --network edulution-prepare \
  postgres:16 2>&1 > /dev/zero

docker run -d \
  --name edulution-keycloak \
  --restart always \
  --env-file ${DIRECTORY}edulution.env \
  -v ${DIRECTORY}realm-edulution.json:/opt/keycloak/data/import/realm-edulution.json \
  -e KC_DB_URL=jdbc:postgresql://edulution-keycloak-db/keycloak \
  -e KC_DB=postgres \
  -e KC_DB_URL_DATABASE=keycloak \
  -e KC_DB_SCHEMA=public \
  -e KC_PROXY=edge \
  -e KC_HOSTNAME_STRICT=false \
  -e KC_HOSTNAME_STRICT_HTTPS=false \
  -e KC_HTTP_RELATIVE_PATH=/auth \
  -p 8080:8080 \
  --network edulution-prepare \
  quay.io/keycloak/keycloak:25.0 \
  start-dev \
  --import-realm 2>&1 > /dev/zero

attempt=0
until $(curl --output /dev/null --silent --get --fail "http://localhost:8080/auth/realms/master"); do
    attempt=$((attempt+1))
  
    if [ $attempt -ge 30 ]; then
        echo "[!] Es konnte kein Verbindung zum Authentifizierungserver hergestellt werden!"
        exit 1
    fi

    echo "[*] Warten bis der Authentifizierungserver gestartet ist (Versuch ${attempt} / 30)"
    sleep 3
done

source ${DIRECTORY}edulution.env

AUTH_TOKEN=$(curl -s --request POST 'http://localhost:8080/auth/realms/master/protocol/openid-connect/token' \
                --header 'Content-Type: application/x-www-form-urlencoded' \
                --data-urlencode "username=${KEYCLOAK_ADMIN}" \
                --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}" \
                --data-urlencode 'grant_type=password' \
                --data-urlencode 'client_id=admin-cli' | jq '.access_token' | sed 's/\"//g')

if [ -z "${AUTH_TOKEN}" ]; then
    echo "[!] Es konnte kein Verbindung zum Authentifizierungserver hergestellt werden!"
    exit 1
fi

KEYCLOAK_PUBLIC_KEY=$(curl -s --request GET 'http://localhost:8080/auth/admin/realms/edulution/keys' \
                        --header "Authorization: Bearer ${AUTH_TOKEN}" \
                        --header 'Content-Type: application/json' | jq '.keys[] | select(.algorithm == "RS256") | .publicKey' | sed 's/\"//g')

KEYCLOAK_CERTIFICATE_KEY=$(curl -s --request GET 'http://localhost:8080/auth/admin/realms/edulution/keys' \
                        --header "Authorization: Bearer ${AUTH_TOKEN}" \
                        --header 'Content-Type: application/json' | jq '.keys[] | select(.algorithm == "RS256") | .certificate' | sed 's/\"//g')

if [[ -z "${KEYCLOAK_PUBLIC_KEY}" && -z "${KEYCLOAK_CERTIFICATE_KEY}" ]]; then
    echo "[!] Die Authentifizierungsschlüssel konnten nicht abgerufen werden!"
    exit 1
fi

cat <<EOF > ${DIRECTORY}data/edulution.pem
-----BEGIN CERTIFICATE-----
${KEYCLOAK_CERTIFICATE_KEY}
-----END CERTIFICATE-----

-----BEGIN PRIVATE KEY-----
${KEYCLOAK_PUBLIC_KEY}
-----END PRIVATE KEY-----
EOF

docker stop edulution-keycloak 2>&1 > /dev/zero
docker stop edulution-keycloak-db 2>&1 > /dev/zero
docker rm edulution-keycloak 2>&1 > /dev/zero
docker rm edulution-keycloak-db 2>&1 > /dev/zero
docker network rm edulution-prepare 2>&1 > /dev/zero

echo "[*] Arbeiten am Authentifizierungserver abgeschlossen."

echo "[*] Konfiguration abgeschlossen. Starte edulutionUI!"
