#!/bin/bash

###########################################################
# Installer for edulutionUI
# V1.0
# by lukas.spitznagel@netzint.de
###########################################################

DIRECTORY="/srv/docker/edulution-ui/"

clear

cat <<EOF
           _       _       _   _             _   _ ___ 
   ___  __| |_   _| |_   _| |_(_) ___  _ __ | | | |_ _|
  / _ \/ _\` | | | | | | | | __| |/ _ \| '_ \| | | || | 
 |  __/ (_| | |_| | | |_| | |_| | (_) | | | | |_| || | 
  \___|\__,_|\__,_|_|\__,_|\__|_|\___/|_| |_|\___/|___|
                                                       
                edulutionUI - Installer

EOF

if [ "$EUID" -ne 0 ]; then
  echo "[!] Bitte führen Sie das Skript mit Root-Rechten aus."
  exit 1
fi

if [ -d "$DIRECTORY" ]; then
  echo "[!] Die edulutionUI scheint bereits installiert zu sein. Bitte prüfe das Verzeichnis '$DIRECTORY'!"
  exit 1
fi


if ! command -v docker &> /dev/null; then
    echo "[*] Docker ist nicht installiert. Installation wird gestartet..."

    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    else
        echo "[!] Betriebssystem konnte nicht ermittelt werden."
        exit 1
    fi

    if [ "$OS" == "ubuntu" ] && ([[ "$VERSION" == "22.04" ]] || [[ "$VERSION" == "24.04" ]]); then

        apt-get update

        apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
            gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

        apt-get update

        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        systemctl enable docker --now

        echo "[*] Docker wurde erfolgreich installiert."

    else
        echo "[!] Dieses Skript unterstützt nur Ubuntu 22.04 und 24.04."
        exit 1
    fi
else
    echo "[*] Docker ist bereits installiert."
fi

echo "[*] Erstelle Ordner für die edulutionUI installation..."
mkdir -p $DIRECTORY

echo "[*] Herunterladen der docker-compose.yml - Datei..."
curl -s -o ${DIRECTORY}docker-compose.yml https://get.edulution.io/docker-compose.yml

if [ ! -f "${DIRECTORY}docker-compose.yml" ]; then
    echo "[!] Datei konnte nicht heruntergeladen werden!"
    exit 1
fi

echo "[*] Starte den edulutionUI Web-Installer..."

docker pull ghcr.io/edulution-io/edulution-installer:main 2>&1 > /dev/zero

cat <<EOF

########################################################

    edulutionUI Web-Installer
      
    Sie erreichen die Oberfläche wie folgt:
      
    https://$(hostname):8000
    https://$(hostname -I | awk '{print $1}'):8000

########################################################

EOF

docker run -it -p 8000:8000 -v /srv/docker/edulution-ui:/edulution-ui/ ghcr.io/edulution-io/edulution-installer:main 2>&1 > /dev/zero